# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lumber Jacking Ninja Pirates
email: akirbypaulini@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 "This website is too cool for you, just like I am"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: akirbypaulini
github_username:  akirbypaulini

# Build settings
markdown: kramdown
